travis:
  secure:
    BINSTAR_TOKEN: ZReWj5FVgE3XXZ3jKvwFijr4pSK7R/FJHMi5jx56Fgm3s7QUZk7RInIcRaG7q9W2AQHfL8gEOgid5qf0nhKuAEseFlETBxxWOgKbVKorwbk+tsZT0NNlam+gwcR6MkWvt1cAMOTUaUgmR5dWi77VQEXwLblp2GXi5bt2fFtZcEwWEYJvn7hdEI822mkIBjQHw1WCbzzqEGTncZtNxqwksmkq5bncc6Bu1Chp8ragP5WrD0bwVEs6ZYmcjIZRmQ0/rmXj0VNKPxt6EcF8VSKA4JM+JDBfpxJKWmHl3G+e1XkkUgIhQAb8YRngZpqhtXIER22qA1WfGT3wQC1jTUi93pGoUi7Jzgia/b7zrCL8GVovVwqkGpBnqAXJjMoAs9cvPrruvvyvgSpIsHVOJeVaohdIpPfuknymHlfjk+Jlr3qgwRdsn9TLs1WwbfE6uwBFv71OslNGl9SvctsLmKN/YU0tle9160LWG83CGeIc0j6Dbon2xvHJM8QAo2ZavM6Elm/BAA1AUbaXt5C6gEYDIZAMUdEm1qTAB5EkZhN2KIpxAwf2y4WUGZxcwgCsXm0btjJ0x49yT7955kWhsg68SQtUeHmcJIcJwneBc/nA/pivRtEZCLk1VOCVRMFSNzzZFBJNMy0E/oXDjJtHUKQ3VxvW3UrjI8anBlXOB1wTnS4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
