travis:
  secure:
    BINSTAR_TOKEN: w6XfoVAlXk3UASpxGgh21Eg9X/7Dd/bkBdUbLyxijgLxVkkkAJdiwCHVifaiqt8WG2wWBvekzrMF8GZ03SpE3HDhXOH8RRIJhyALUIoNgCo+pypAEBTlvtULTR8ssKPANST7rYVnZTPiyKvoTUJs7bclVcgaTXM0X7cbbEmlcWhEs1M/q12YkYdH4FH8DQnU5aL0bm/rPiQSqgF0zubUi+0riOJ/eVMTV+nUiWT0OMwl2wnvfUsXHMfbJ7cP7BWHtGQgC/C2AAC1/KjOoa9Wdp3TEMWXS63Kml1Z0oCHZ8CLXTtEOKZPAXDTl3mjkbfdXgvytqwMqrcDcbtOuN1V/ZktvAFRpawGK7HhW8vnCDC1WzANoy+SBPee+kLXVpY/tYyFYrK0XHgfTuIvvl54vAJcBhKNiQQeOFEfMKo7qAp/sjqoDBEEFRWCDnbBqOJ0hffI9IMRKYnbgA1DU1O3d4VOk2t/kKIls90xRDsmL0aWxWRtDhEquFnseSji4VeQtxRhqLyVEVw11e6cwV/H1zvi086W7slYNOjm6jTVznmANoZwVnPzhHBT0ub9R3grD/c1e6XcfUdd8O68+/p9ClUsJ/xK2bjEa7w53/ZVMTsbPNua69cl6kPoQht+GkwkrGvJBRtJS6DQEr2WxP1mLWXJzZoHFxZqblaTiFyPWmU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
